
n_epochs: <NUMBER OF EPOCHS>

data:
  directory: models
  experiment: apax
  data_path: <PATH>

  n_train: 1000
  n_valid: 100
  batch_size: 4
  valid_batch_size: 100

metrics:
  - name: energy
    reductions: [mae]
  - name: forces
    reductions: [mae, mse]

loss:
  - name: energy
  - name: forces
    weight: 4.0
